apiVersion: v1
kind: Pod
metadata:
  name: kasm-agent-container
  labels:
    app: kasm-agent-container
spec:
  imagePullSecrets:
    - name: my-registry-secret
  containers:
  - name: kasm-agent-container
    image: hallros/agent:experimental
    imagePullPolicy: Always
    securityContext:
      privileged: true
    ports:
    - name: https
      containerPort: 443
    - name: health
      containerPort: 4444
    livenessProbe:
      httpGet:
        path: /__healthcheck
        port: 4444
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 10
    readinessProbe:
      httpGet:
        path: /__healthcheck
        port: 4444
      initialDelaySeconds: 30
      periodSeconds: 5
      timeoutSeconds: 5
    env:
    volumeMounts:
    - name: ssl-cert-volume
      mountPath: /host/certs
    - name: agent-config
      mountPath: /opt/kasm/current/conf/agent.app.config.yaml
    resources:
      limits:
        memory: "8000Mi"
        cpu: "4000m"
      requests:
        memory: "4000Mi"
        cpu: "2000m"
  restartPolicy: Always
  volumes:
  - name: ssl-cert-volume
    hostPath:
      path: /etc/ssl/certs
      type: Directory
  - name: agent-config
    hostPath:
      path: /home/hallros/kasm-agent/runtime/agent.app.config.yaml
